import Footer from "@/src/components/GlobalComponents/footerComponents/Footer";
import MenuWrapper from "@/src/components/GlobalComponents/headerComponents/MenuWrapper";

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}
 
export default function RootLayout({ children }) {
 return (
   <html lang="en">
     <body>
       <MenuWrapper />

       {children}
       <Footer />
     </body>
   </html>
 );
}
