import ClientProvider from "./ClientProvider";
import ClientProviterTheme from "./ClientProviterTheme";
import "./globals.css";
import { Inter } from "next/font/google";
const inter = Inter({ subsets: ["latin"] });
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ClientProvider>
          <ClientProviterTheme>{children}</ClientProviterTheme>
        </ClientProvider>
      </body>
    </html>
  );
}
