import ClientProviderTheme from "./ClientProviderTheme";
import ClientProvider from "./ClientProvider";

import "./globals.css";
import { Inter } from "next/font/google";
import Menu from "./components/headerComponent/Menu";
import Footer from "./components/footerComponent/Footer";
const inter = Inter({ subsets: ["latin"] });
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <ClientProvider>
        <ClientProviderTheme>
          <body className={inter.className}> 
          <Menu/>
          {children}
          <Footer/>
          </body>
        </ClientProviderTheme>
      </ClientProvider>
    </html>
  );
}
